# Generated by Django 3.1.6 on 2021-06-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0008_auto_20210429_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicgeneral',
            name='cAutonoma',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.region', verbose_name='Region'),
        ),
    ]
